services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/back/dockerfile
    container_name: wordle_backend
    ports:
      - "${BACK_PORT}:${BACK_PORT}"
    env_file:
      - .env
    environment:
      BACK_HOST: ${BACK_HOST}
      BACK_PORT: ${BACK_PORT}
    depends_on:
      - database
    command: [
      "poetry", "run",
      "uvicorn", "src.app:app",
      "--host", "${BACK_HOST}",
      "--port", "${BACK_PORT}"
    ]

  database:
    image: postgres:14.4-alpine
    container_name: wordle_backend_postgres
    restart: always
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}

      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
